export const MANAGE_RUN_ACTIONS = {
  SAVE_RUN: 'SAVE_RUN',
  SAVE_RUN_REQUEST: 'SAVE_RUN_REQUEST',
  SAVE_RUN_COMPLETED: 'SAVE_RUN_COMPLETED',
  SAVE_RUN_FAILED: 'SAVE_RUN_FAILED',

  GET_RUN: 'GET_RUN',
  GET_RUN_REQUEST: 'GET_RUN_REQUEST',
  GET_RUN_RECEIVED: 'GET_RUN_RECEIVED',
  GET_RUN_FAILED: 'GET_RUN_FAILED',

  UPDATE_RUN: 'UPDATE_RUN',
  UPDATE_RUN_REQUEST: 'UPDATE_RUN_REQUEST',
  UPDATE_RUN_COMPLETED: 'UPDATE_RUN_COMPLETED',
  UPDATE_RUN_FAILED: 'UPDATE_RUN_FAILED'
};